/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.10
 * Generated at: 2025-10-25 11:51:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.quiz.model.Question;

public final class quiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.quiz.model.Question");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

List<Question> questions = (List<Question>) request.getAttribute("questions");
if (questions == null) {
    out.println("<h3 style='color:red'>Error: No questions loaded. Please access via /QuizServlet or check your DB.</h3>");
    return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Online Quiz</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* RESET and BASE STYLES */\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; /* A more modern font */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f0f2f5; /* Light background */\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: flex-start;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        padding: 40px 20px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* MAIN CONTAINER */\r\n");
      out.write("    .quiz-container {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 700px; /* Slightly narrower for focus */\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); /* Softer shadow */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        color: #1877f2; /* A nice primary color */\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    form {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 30px; /* Space between question blocks */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* QUESTION BLOCK STYLING */\r\n");
      out.write("    .question-block {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        border: 1px solid #e1e4e8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .question-block b {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* OPTION STYLING (THE FIX FOR ALIGNMENT) */\r\n");
      out.write("    .option {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center; /* Vertically centers the radio button and text */\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .option:hover {\r\n");
      out.write("        background-color: #eaf1fb; /* Subtle hover effect */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .option input[type=\"radio\"] {\r\n");
      out.write("        /* Use default browser styling, but ensure size and color */\r\n");
      out.write("        accent-color: #1877f2;\r\n");
      out.write("        transform: scale(1.1);\r\n");
      out.write("        margin-right: 15px;\r\n");
      out.write("        width: 18px;\r\n");
      out.write("        height: 18px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .option-label {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        flex-grow: 1; /* Allows label to take up remaining space */\r\n");
      out.write("        padding-top: 2px; /* Fine-tune vertical alignment of text */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* SUBMIT BUTTON */\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("        background: #1877f2;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        padding: 12px 0;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background 0.3s ease;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("        background: #145cb3;\r\n");
      out.write("        box-shadow: 0 6px 8px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .quiz-container {\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"quiz-container\">\r\n");
      out.write("        <h2>Answer the following questions:</h2>\r\n");
      out.write("        <form action=\"ResultServlet\" method=\"post\">\r\n");
      out.write("            ");

            int i = 1;
            for (Question q : questions) {
            
      out.write("\r\n");
      out.write("            <div class=\"question-block\">\r\n");
      out.write("                <b>Q");
      out.print(i++);
      out.write('.');
      out.write(' ');
      out.print(q.getQuestion());
      out.write("</b>\r\n");
      out.write("                \r\n");
      out.write("                <label class=\"option\">\r\n");
      out.write("                    <input type=\"radio\" name=\"answer_");
      out.print(q.getId());
      out.write("\" value=\"A\">\r\n");
      out.write("                    <span class=\"option-label\">");
      out.print(q.getOptionA());
      out.write("</span>\r\n");
      out.write("                </label>\r\n");
      out.write("                \r\n");
      out.write("                <label class=\"option\">\r\n");
      out.write("                    <input type=\"radio\" name=\"answer_");
      out.print(q.getId());
      out.write("\" value=\"B\">\r\n");
      out.write("                    <span class=\"option-label\">");
      out.print(q.getOptionB());
      out.write("</span>\r\n");
      out.write("                </label>\r\n");
      out.write("                \r\n");
      out.write("                <label class=\"option\">\r\n");
      out.write("                    <input type=\"radio\" name=\"answer_");
      out.print(q.getId());
      out.write("\" value=\"C\">\r\n");
      out.write("                    <span class=\"option-label\">");
      out.print(q.getOptionC());
      out.write("</span>\r\n");
      out.write("                </label>\r\n");
      out.write("                \r\n");
      out.write("                <label class=\"option\">\r\n");
      out.write("                    <input type=\"radio\" name=\"answer_");
      out.print(q.getId());
      out.write("\" value=\"D\">\r\n");
      out.write("                    <span class=\"option-label\">");
      out.print(q.getOptionD());
      out.write("</span>\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("            <input type=\"submit\" value=\"Submit Quiz\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
